{% set name = "rastervision-aws-s3" %}
{% set version = "0.20.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rastervision_aws_s3-{{ version }}.tar.gz
  sha256: 91134c49013ff2c19de2fb2820c96c22be9290ca9186b839b70b253cf67b687a
  patches:
    - 0001-fix-imports.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - rastervision=rastervision.aws_s3.s3_file_system:main

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - awscli
    - boto3
    - python >=3.6
    - rastervision-pipeline ==0.13.1

test:
  imports:
    - rastervision.aws_s3
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/azavea/raster-vision
  summary: A rastervision plugin that adds an AWS S3 file system
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - psortos
